SELECT * FROM useranswers;

SELECT * FROM question; /* Need LookOver but Done */
SELECT * FROM user; /* Backend Done */
SELECT * FROM category; /* Done */
SELECT * FROM quiz; /* Done */
SELECT * FROM questionchoice; /* Done */

/*USER*/
INSERT INTO user (firstName,lastName,gender,email,password,phoneNumber,access) VALUES ();

/* CATEGORY */
INSERT INTO category (categoryName) values ('Test');

/* QUIZ */
INSERT INTO quiz (quizName,Description,created) VALUES ('BasicMath','Eazy math questions.',Now());
/*Quiz Update */
UPDATE quiz SET quizName='UpdatedQuiz', Description='ThisWasUpdated', created=Now() where id= 1;

/* QUESTION */
INSERT INTO question (id,question,categoryId,quizId) 
VALUES (1, '1+1=?',(SELECT id FROM category WHERE id =1),(SELECT id FROM quiz WHERE id =1));

/* QUESTIONCHOICE */
INSERT INTO questionchoice (choice,questionId,points) VALUES ('2',(SELECT id FROM question WHERE id = 1),3);


UPDATE questionchoice SET choice='Test',questionId='3', points='3' where id= 10;




SELECT * FROM useranswers WHERE userId


UPDATE question SET question=?, categoryId=?, quizId=? WHERE id = ?;

DELETE FROM question WHERE id =1;


/* UserAnswers */

INSERT INTO useranswers (userId,questionId,questionChoiceId,quizId) VALUES ((SELECT id FROM user WHERE id = 2),(SELECT id FROM question WHERE id = 1),(SELECT id FROM questionchoice WHERE id = 8),(SELECT id FROM quiz WHERE id = 1));


/*Test adatok*/

/*Category Feltöltése*/
INSERT INTO category (id,categoryName) VALUES 
(1,'Art'),
(2,'Business'),
(3,'Computer science'),
(4,'English Language Arts'),
(5,'Finance'),
(6,'General knowledge'),
(7,'Geography'),
(8,'History'),
(9,'Languages'),
(10,'Law'),
(11,'Math'),
(12,'Music'),
(13,'Science'),
(14,'Seasonal'),
(15,'Social Emotional Learning'),
(16,'Social studies'),
(17,'Trivia');


/*Quiz Feltöltése*/
INSERT INTO quiz
(id,quizName,Description,created,categoryId)
VALUES 
(1,'Famous Art!','Can you name all these famous artworks?',NOW(),1),
(2,'UNDERSTANDING BALANCE IN ART','Can you identify the balance is these pictures?',NOW(),1),
(3,'Art 101: Elements of Art','Elements of Art',NOW(),1),
(4,'Business','Business',NOW(),2),
(5,'Introduction to Business Management','This is the introduction chapter to test how much you know about management. Lets begin...',NOW(),2),
(6,'C1 Vocabulary: Business English','Business Vocabulary',NOW(),2),
(7,'KS4 End of Term Computer Science Quiz','A series of questions from all over the realm of Computer Science, some will be guesses for your students but all will be fun!',NOW(),3),
(8,'Computer Science Trivia','Time to have fun with this quiz about computer trivia. Answer these computer science trivia questions and become the master of computers!',NOW(),3),
(9,'Problem Solving Process','Based on the Unit 1 curriculum from Code.org, this quiz reviews the problem solving process concepts in Chapter 1.',NOW(),3),
(10,'English Language Arts Review- Grammar','Used for end of year review',NOW(),4),
(11,'4th Grade English/Language Arts','fourthgrade English',NOW(),4),
(12,'2nd Grade English Language Arts','Flex Day 1',NOW(),4),
(13,'Personal Finance Basics (Middle School)','Learn the basics of personal finance for middle school and junior high school students.',NOW(),5),
(14,'Real Estate Finance Study Guide','This is a study guide for my students enrolled in the 30 classroom hour pre-license finance course',NOW(),5),
(15,'Finance Business Studies HSC','Business Studies',NOW(),5),
(16,'The United Nations (UN)','A quiz on the #history and purpose of the United Nations in celebration of United Nations Day.',NOW(),6),
(17,'U.S. Government and Politics','A socialstudies quiz about unitedstates politics and government.',NOW(),6),
(18,'World War I: Overview','A kahoot about the major events of World War I.',NOW(),6),
(19,'Geography Review','A geography review of major world countries and continents and oceans.',NOW(),7),
(20,'European Geography','european geography',NOW(),7),
(21,'Nature Geography','geography in the forest, on land, and in water, 24 questions about nature, environment, region (Animals, Mountains, Forests, Deserts, etc.)',NOW(),7),
(22,'Teens Who Made History','A fun history Quiz about teenagers who changed the world.',NOW(),8),
(23,'World History: The Renaissance','How much do you know about the Renaissance? Take this quiz to find out!',NOW(),8),
(24,'History of Halloween','A history Halloween Quiz to see what students know.',NOW(),8),
(25,'European Day of Languages Challenge','EDL',NOW(),9),
(26,'World Languages Orientation Day','trivia',NOW(),9),
(27,'I love you in different languages.','Do you know in which language "I love you �" is said like this? Test your knowledge with this fun language quiz',NOW(),9),
(28,'Physics: Newtons 3rd Law','This quiz reviews Newtons 3rd Law of Motion and provides several examples to help understand the relationship between two',NOW(),10),
(29,'Ethics in Law Enforcement','Ethics in Law Enforcement',NOW(),10),
(30,'Contract Law Test Review','Law Test',NOW(),10),
(31,'Ratios, Proportions, Solving Proportions (MATH)','Use ratio and rate reasoning to solve real-world and mathematical problems',NOW(),11),
(32,'Math Order of Operations Back-to-School','A back-to-school refresher!',NOW(),11),
(33,'Algebra Rearrange Formulas (MATH)','Rearrange formulas to highlight a quantity of interest, using the same reasoning as in solving equations.',NOW(),11),
(34,'Intro to Instrumental','An introduction to instrumental through performance and music techniques from renowned Disney entertainment!',NOW(),12),
(35,'Music 2021','Music 2021',NOW(),12),
(36,'Holiday Music Trivia','Play this kahoot to see how much you know about holiday songs!',NOW(),12),
(37,'Superbugs!','Superbugs!',NOW(),13),
(38,'Regeneration','Regeneration',NOW(),13),
(39,'Earth & Space Science with Star Wars','This Quiz explores various Earth and space science trivia using comparisons from StarWars.',NOW(),13),
(40,'Seasonal produce','Show the class how much you know!',NOW(),14),
(41,'Seasonal Changes','Seasonal Changes',NOW(),14),
(42,'Climate Change','Use this quiz to test your knowledge on climatechange.',NOW(),14),
(43,'Social-Emotional Learning','This quiz introduces the five key areas of social-emotional learning and ways to practice each one! ',NOW(),15),
(44,'Find Your Spark with Pixars Soul','New souls discover their personalities at the You Seminar in Pixars OSCAR® Winner Soul. Explore what makes everyone unique in this special quiz. ',NOW(),15),
(45,'Always Let Your Conscience Be Your Guide!','Doing what is right isnt always easy, but when you let your conscience be your guide, it can help you make the good decisions! Learn how to make good decisions with Pinocchio. ',NOW(),15),
(46,'Empathy','Empathy - This kahoot helps children ages 6+ practice sharing and relating to others feelings by connecting over shared experiences.',NOW(),16),
(47,'Elections in America','Covering the serious business of elections in America in a not-so-serious way.',NOW(),16),
(48,'Critical Thinking','Critical Thinking - This kahoot helps children ages 6+ understand the difference between assumptions and facts and the importance of asking questions. ',NOW(),16),
(49,'General Trivia','Hey, trivia master! Surprise your friends with this quiz. Who will hit this one out of the park?',NOW(),17),
(50,'Seven Wonders of the Ancient World','A geography quiz about the Seven Wonders of the Ancient World. See how much you know about these ancient buildings and monuments!',NOW(),17),
(51,'Famous European artists and their paintings','Do you like art? Do you want to learn more about some of the famous painters in history? Then this inspiring quiz is for you!',NOW(),17);


/*Question Feltöltése*/

/*10 DB*/
(,'',),
(,'',),
(,'',),
(,'',),
(,'',),
(,'',),
(,'',),
(,'',),
(,'',),
(,'',),
INSERT INTO question
(id,question,quizId)
VALUES
(1,'Name the artwork!',1),
(2,'Name the artwork!',1),
(3,'Name the artwork!',1),
(4,'Name the artwork!',1),
(5,'Name the artwork!',1),
(6,'Name the artwork!',1),
(7,'Name the artwork!',1),
(8,'Name the artwork!',1),
(9,'Look at the picture and identify the type of ballance.',2),
(10,'Look at the picture and identify the type of ballance.',2),
(11,'Look at the picture and identify the type of ballance.',2),
(12,'Look at the picture and identify the type of ballance.',2),
(13,'Look at the picture and identify the type of ballance.',2),
(14,'Look at the picture and identify the type of ballance.',2),
(15,'Look at the picture and identify the type of ballance.',2),
(16,'Look at the picture and identify the type of ballance.',2),
(17,'Look at the picture and identify the type of ballance.',2),
(18,'Look at the picture and identify the type of ballance.',2),
(19,'Look at the picture and identify the type of ballance.',2),
(20,'Look at the picture and identify the type of ballance.',2),
(21,'Look at the picture and identify the type of ballance.',2),
(22,'Look at the picture and identify the type of ballance.',2),
(23,'Look at the picture and identify the type of ballance.',2),
(24,'Look at the picture and identify the type of ballance.',2),
(25,'Look at the picture and identify the type of ballance.',2),
(26,'Look at the picture and identify the type of ballance.',2),
(27,'Look at the picture and identify the type of ballance.',2),
(28,'Look at the picture and identify the type of ballance.',2),
(29,'Look at the picture and identify the type of ballance.',2),
(30,'Look at the picture and identify the type of ballance.',2),
(31,'Look at the picture and identify the type of ballance.',2),
(32,'Look at the picture and identify the type of ballance.',2),
(33,'Look at the picture and identify the type of ballance.',2),
(34,'Look at the picture and identify the type of ballance.',2),
(35,'Look at the picture and identify the type of ballance.',2),
(36,'Look at the picture and identify the type of ballance.',2),
(37,'Look at the picture and identify the type of ballance.',2),
(38,'Look at the picture and identify the type of ballance.',2),
(39,'Another name of this Element of Art is hue:',3),
(40,'This Element of Art is a path of a point moving throught space.',3),
(41,'This element of Art implies spatial form and is usually perceived as two-dimensional (flat)',3),
(42,'This has depth,lenght,and width and resides in space.It is perceived as three-dimensinal',3),
(43,'An enclosed space,the boundaries of which are defined by other elements of art.',3),
(44,'These all come from the three primaries and black and white.',3),
(45,'This refers to relative lightness & darkness & is perceived in varying levels of cantrast.',3),
(46,'These are limited to two dimensions: length and width',3),
(47,'This refers to the area in which art is organized.',3),
(48,'This represents a value of space or a 3-dimensional object on a flat surface.',3),
(49,'This refers to tactile qualities of a surface or visual representation of surface qualities.',3),
(50,'These shapes have natural, less well-defined edges (think: an amoeba, or a cloud)',3),
(51,'These shapes have the clear edges one achives when using tools to create them.',3),
(52,'This Element of Art has three proerties - hue,value,and intensity.',3),
(53,'The three primary colors are:',3),
(54,'Which statement is true?',4),
(55,'Which of the following is NOT a commodity:',4),
(56,'The prics of petrol rises, which statement best descripes the effect on a small delivery firm:',4),
(57,'The price of chocolate falls. Which statement best describes the reason why this has happened.',4),
(58,'If intrest rates fall:',4),
(59,'If the intrest rate rises:',4),
(60,'Which statement best describes an export for a UK firm:',4),
(61,'If £1 = $1.80, then a £1,000 order of British cheese will sell in the USA for:',4),
(62,'If £1 = $1.50, then a $450 weekend break in Wen York will cost a UK customer:',4),
(63,'If the £ is weaker:',4),
(64,'If the £ becomes stronger:',4),
(65,'If firms can correctly forecast future economic conditions:',4),
(66,'What are the factors of production?',4),
(67,'What is the basic economic problem?',4),
(68,'Which is NOT a bisiness objective?',4),
(69,'Value added is...',4),
(70,'What does FIFO stand for?',4),
(71,'Which country is the biggest producer of natural gas?',4),
(72,'What is the larges stock exchange in the world in therms of market capitalisation?',4),
(73,'What county had the highest crude oil prouction in 2014?',4),
(74,'Which nation is not a member of the Asia-Pacific Economic Cooperation (APEC)?',4),
(75,'Which of the following countries is not one of three larges trade partners of the USA?',4),
(76,'What year did NAFTA enter into force?',4),
(77,'Which of the following is the most expensive currency?',4),
(78,'Which city has the highest cost of living?',4),
(79,'Management: A process of using organisational resources to achive organisations goals by Planning, Organising __ & __',5),
(80,'____ was the first to describe the four managerial functions in 1800s.',5),
(81,'Leadership involves a maneger using power, infuence, vision, persuasion, and communication skills.',5),
(82,'___ is to eliminate jobs at all levels of management.',5),
(83,'___ is expanding the tasks and responsibilities of the employees.',5),
(84,'There are 3 broad categories of Roles are - Interpersonal Informational & ____.',5),
(85,'Associated with the tasks needed to obtain and transmit information for manegment of the organisation.',5),
(86,'The manager trasmits information to influence attitudes and behaviour of employees.',5),
(87,'The Three skils that manegers need to perform effectively are Conceptual, Human & ___ Skills',5),
(88,'___ seeks to negotiate solutions between manegers, unions, customers and of shareholders.',5),
(89,'In the hotel industry, we need to be able to offer more than our ______.',6),
(90,'{Once you''ve finished the work, you can ______ for the work completed.',6),
(91,'A person who works in _______ helps find new employees for a company.',6),
(92,'A person who works in public relations helps promote a good image of someone or a company.',6),
(93,'His company buys and sells shares on the ____ market.',6),
(94,'In order for our business to be profitable, we need a better advertising ______.',6),
(95,'We should probably choose the lowest of the three ______ for the building work.',6),
(96,'After years of trading, the business was finally a ______ success.',6),
(97,'Knowing exchange rates is vital for ______ trading.',6),
(98,'Which word cannot be a noun and a verb?',6),
(99,'What does the abbreviation D.N.S. stand for?',7),
(100,'Put these in order of size',7),
(101,'What is a Boolean?',7),
(102,'In Python the get() belonging to a dictionary does what?',7),
(103,'In Python a List uses what type of brackets when it is created?',7),
(104,'What does LAN stand for?',7),
(105,'Lossy or Lossless: Which has better quality?',7),
(106,'Which one isn''t a protocol?',7),
(107,'Which is the odd one out?',7),
(108,'Which is the odd one out?',7),
(109,'RAM is which statement?',7),
(110,'What is secondary storage?',7),
(111,'What does CPU stand for?',7),
(112,'During the Fetch Execute cycle...',7),
(113,'During the Fetch Execute cycle...',7),
(114,'42 in binary is...?',7),
(115,'30 in Hex is...?',7),
(116,'I need to decide between two paths.  Do I use a...',7),
(117,'An NIC is?',7),
(118,'Port 80 is mainly for?',7),
(119,'An example of encryption is?',7),
(120,'A runtime error prevents...',7),
(121,'Which is the odd one out?',7),
(122,'FTP is for the transfer of...',7),
(123,'HTML stands for?',7),
(124,'16 in binary is?',7),
(125,'A string can be...?',7),
(126,'A signed integer allows...',7),
(127,'IP stands for?',7),
(128,'Zero in binary is?',7),
(129,'The controller sends a control signal to (blank) telling it to read data? What is the (blank)?',7),
(130,'Which one doesn''t have an affect on the speed of a CPU?',7),
(131,'How many cycles per second is 1 Ghz?',7),
(132,'R.I.S.C. is an abbreviation for?',7),
(133,'Which is designed to be faster RAM or Cache Memory?',7),
(134,'Which is not an advantage of a solid state drive?',7),
(135,'Which is not a feature of a Graphical User Interface?',7),
(136,'Truth table: A=1 and B=1 | A AND B will OUTPUT?',7),
(137,'Truth table: A=1 and B=0 | A AND B will OUTPUT?',7),
(138,'Truth table: A=1 and B=0 | A OR B will OUTPUT?',7),
(139,'Truth table: A=0 and B=0 | A OR B will OUTPUT?',7),
(140,'How many bits in a byte?',7),
(141,'Sound is converted into a digital value by a process called....?',7),
(142,'Which one is not a function of an Operating System?',7),
(143,'A firewall is designed to...',7),
(144,'An assembler is a program that...',7),
(145,'Which one is a principle of the Data Protection Act?',7),
(146,'The Computer Misuse Act is not designed to prevent....',7),
(147,'Which is not a stage of compilation?',7),
(148,'A variable name should...',7),
(149,'23 in binary is?',7),
(150,'16 in Hex is?',7),
(151,'What am I: Looking for a number in an list of numbers one by one until I find the number',7),
(152,'How many bits in a nibble?',7),
(153,'What is the name of the first computer? ',8),
(154,'Which of the following is NOT a programming language?',8),
(156,'What computer device got its name because the cord looked like the tail of this animal?',8),
(157,'Which social media is the newest?',8),
(158,'What letter is between Q and E on a computer keyboard?',8),
(159,'Who came up with the phrase "computer bug"?',8),
(160,'What critter was the first computer 'bug'?',8),
(161,'Who was the first computer programmer?',8),
(162,'What did Charles Babbage invent when he designed his analytical engine in 1833?',8),
(163,'What is the name of the IBM computer that beat Jeopardy champions?',8),
(164,'What is the popular name for the small icons commonly used to describe emotions?',8),
(165,'Select all the computer manufacturers that were started in a garage.',8),
(166,'What does www stand for?',8),
(167,'Who co-founded Microsoft?',8),
(168,'What part of a computer is the "brain"?',8),
(169,'How many solutions exist for any given problem?',9),
(170,'What is the first stage of the Problem Solving Process?',9),
(171,'There are ___ primary steps in the Problem Solving Process.',9),
(172,'Solutions can always be improved.',9),
(173,'Which of these is part of the PREPARE stage?',9),
(174,'The Problem Solving Process can only be used to complete computer-based tasks.',9),
(175,'"Carry out your plan" best describes this stage',9),
(176,'Step 2 of the Problem Solving Process is where this action takes place:',9),
(177,'Solutions should be as complex and detailed as possible to be successful.',9),
(178,'What is a noun?',10),
(179,'What is the job of a verb?',10),
(180,'What does an adjective do?',10),
(181,'What is an adverb?',10),
(182,'What is the job of a preposition?',10),
(183,'What is the job of a pronoun?',10),
(184,'Conjunctions join what three things:',10),
(185,'What do we use to remember coordinating conjunctions?',10),
(186,'What is the difference between common and proper nouns?',10),
(187,'Jessie walked happy to school. |  What is wrong with the sentence?',10),
(188,'Which of the following are NOT a subject pronoun?',10),
(189,'Which of the following are NOT an object pronoun?',10),
(190,'Mom bought him and I cookies. |  What is wrong with the sentence?',10),
(191,'A coordinating conjunction  should always have what before it if it''s joining to sentences',10),
(192,'What sentence type only shows one complete thought?',10),
(193,'What sentence type has two independent sentences joined together with a conjunction?',10),
(194,'What sentence type has a dependant clause joined by an independent clause?',10),
(195,'A dependent clause ________________.',10),
(196,'A independent clause ________________.',10),
(197,'Subordinating conjunctions will usually always go before a ____________.',10),
(198,'How can you remember the most common subordinating conjunctions?',10),
(199,'The car drove quickly down the road.  | What is the sentence?',10),
(200,'She and I ran to the store, and we grabbed food for dinner. | Sentence type?',10),
(201,'Before we leave, we want to get something for our friend. | Sentence type?',10),
(202,'She went to her friend''s house after she was told not to. | Sentence type?',10),
(203,'Which is a possessive pronoun?',10),
(204,'Which of these pronouns is in first person?',10),
(205,'Which of these pronouns is NOT a 3rd person pronoun?',10),
(206,'Which is NOT an article?',10),
(207,'Which is NOT a preposition?',10),
(208,'Which is an example of a compound word?',11),
(209,'What is the base/root word of the word "REPAINT"?',11),
(210,'All of the following words are prefixes EXCEPT...',11),
(211,'What 2 words make up this contraction?  DON''T',11),
(212,'Fill in the blank:    ______ bike has been missing for 1 week.',11),
(213,'Fill in the blank:  She was going to _______ a letter to her grandma.',11),
(214,'How many syllables does the word | hippopotamus  have?',11),
(215,'What is a synonym for the word generous?',11),
(216,'Which 2 words are antonyms?',11),
(217,'Change the bold word in the following sentence to a pronoun: Ana is reading a book.',11),
(218,'Cause and Effect:  Choose the correct effect for the sentence- Max ate too many marshmallows.',11),
(219,'Commas:  What is the proper way to write this sentence?',11),
(220,'All of the following are sentences except...?',11),
(221,'What''s wrong with this sentence? | What time do you want to meet at the park can we play early? ',11),
(222,'Put the following words in alphabetical order...',11),
(223,'Fill in the blank:  I didn''t do ________ this weekend.',11),
(224,'All of the following are common nouns.  Which one is the proper noun?',11),
(225,'All of the following are examples of similes EXCEPT...',11),
(226,'What is the VERB in the following sentence...  Mary bakes cookies for her birthday.',11),
(227,'Main Idea: Pete is my dog. He can do lots of tricks. When I say "Dance, Pete!" He will dance.',11),
(228,'Which sentence is written correctly?',12),
(229,'Which punctuation mark goes at the end of a question',12),
(230,'Fiction stories are about real things.',12),
(231,'The first letter in a sentence needs to',12),
(232,'A noun is',12),
(233,'Which word should start with a capital letter?',12),
(234,'When you are upset about something you are',12),
(235,'Choose the word that should start with a capital letter',12),
(236,'Choose the correct verb. The boys _____ in the car.',12),
(237,'Which word best completes the sentence? Wendy is ____ wet from the rain.',12),
(238,'Which word means to be more sad than someone else?',12),
(239,'Choose the sentence that is written correctly.',12),
(240,'Choose the word that should start with a capital letter.',12),
(241,'There ____ a big supermarket next to my house.',12),
(242,'Which word represents playing something again?',12),
(243,'Which word means without life?',12),
(244,'Which word best fits in the blank? The school bell rang ____.',12),
(245,'Which month is NOT capitalized correctly?',12),
(246,'Which is a complete sentence?',12),
(247,'He is a teacher. _______ name is Mr. Phillips.',12),
(248,'Choose the noun that names a person',12),
(249,'Which of the following is a complete sentence?',12),
(250,'My friend _____ me for his birthday gift.',12),
(251,'Which of these words is a noun?',12),
(252,'What is the proper end punctuation? I used Sarah Boone''s invention this morning',12),
(253,'Please buy ____ bag of apples at the store.',12),
(254,'The little boy was very careful as he _____ near the ledge.',12),
(255,'Miss Jane gave me ____ last cookie.',12),
(256,'Choose the correct punctuation. Some crickets live outdoors',12),
(257,'His pencil box ____ at home',12),
(258,'What money topic do you know the most about?',13),
(259,'There are many important money topics!',13),
(260,'A budget is a plan for spending and saving your income.',13),
(261,'Which of the following is a “want” instead of a “need”?',13),
(262,'Which of the following is NOT a balanced budget, with a monthly income of $1,000?',13),
(263,'An entrepreneur is a person who …',13),
(264,'If an entrepreneur sells $350,000 in products in one year, and the costs for the year were $175,000, what is the profit?',13),
(265,'If an entrepreneur sells $350,000 in products in one year, and the costs for the year were $175,000, what is the profit?',13),
(266,'Which of the following is NOT true? A credit card ...',13),
(267,'Which of the following is NOT an example of a variable expense in a budget?',13),
(268,'A $60 internet bill is a fixed expense',13),
(269,'Paycheck deductions go toward which type of tax?',13),
(270,'Which of the following is a possible opportunity cost of buying a new pair of $60 sneakers?',13),
(271,'Money from taxes is used to pay for services that are provided by the government.',13),
(272,'Credit card debt tends to have a lower interest rate than other types of debt.',13),
(273,'What should you NOT do when making a major purchase decision?',13),
(274,'',14),
(275,'',14),
(276,'',14),
(277,'',14),
(278,'',14),
(279,'',14),
(280,'',14),
(281,'',14),
(282,'',14),
(283,'',14),
(284,'',14),
(285,'',14),
(286,'',14),
(287,'',14),
(288,'',14),
(289,'',14),
(290,'',14),
(291,'',14),
(292,'',14),
(293,'',14),
(294,'',14),
(295,'',14),
(296,'',14),
(297,'',14),
(298,'',14),
(299,'',14),
(300,'',14),
(301,'',14),
(302,'',14),
(303,'',14),
(304,'',14),
(305,'',14),
(306,'',14),
(307,'',14),
(308,'',14),
(309,'',14),
(310,'',14),
(311,'',14),
(312,'',14),
(313,'',14),
(314,'',14),
(315,'',14),
(316,'',14),
(317,'',14),
(318,'',14),
(319,'',14),
(320,'',14),
(321,'',14),
(322,'',14),
(323,'',14),
(324,'',14),
(325,'',14),
(326,'',14),
(327,'',14),
(328,'',14),
(329,'',14),
(330,'',14),
(331,'',14),
(332,'',14),
(333,'',14),
(334,'',14),
(335,'',14),
(336,'',14),
(337,'',14),
(338,'',14),
(339,'',14),
(340,'',14),
(341,'',14),
(342,'',14),
(343,'',14),
(344,'',14),
(345,'',14),
(346,'',14),
(347,'',14),
(348,'',14),
(349,'',14),
(350,'',14),
(351,'',14),
(352,'',14),
(353,'',14),
(354,'',14),
(355,'',14),
(356,'',14),
(357,'',14),
(358,'',14),
(359,'',14),
(360,'',14),
(361,'',14),
(362,'',14),
(363,'',14),
(364,'',14),
(365,'',14),
(366,'',14),
(367,'',14),
(368,'',14),
(369,'',14),
(370,'',14),
(371,'',14),
(372,'',14),
(373,'',14),
(374,'What objective describes the ability of a business to have cash to pay current liabilities?',15),
(375,'What is an external source of owner’s equity for a public company?',15),
(376,'What type of organisation issues a debenture?',15),
(377,'What source of finance is investment in a private company?',15),
(378,'What source of finance is investment in a private company?',15),
(379,'What is another name for a financial forecast?',15),
(380,'The Accounting Equation is the foundation for which financial statement?',15),
(381,'What do we call the difference between current assets and current liabilities?',15),
(382,'What describes the relationship between debt and equity?',15),
(383,'What is one limitation of financial reports that causes the balance sheet to be inaccurate?',15),
(384,'Which method of international payment has the highest risk for the exporter?',15),
(385,'What do we call a financial contract used for hedging?',15),
(386,'who is my coolest daughter?',15),



